Small fixes for convinient work with 2d data
David-cripto/toySB pull request #2
Opened 2024-05-23 23:57 UTC by ocenandor

1. Change `sample2d.py` to have an oportunity to save raw generated points with `.th` extention 
2. `train2d.py`
    * remove integrator arguments 
    * set default name of experiment - `datetime.now().strftime("%y-%m-%d %H:%M:%S")`
    * checkpoint dir changed to `log_dir / name`
    * add `--ckpt_every` arg to save multiple checkpoints
3. Add multiple checkpointing to `utils.py`
4. Apply isort

2024-05-24 12:42 UTC, David-cripto requested changes
Some changes are not appropriate for merging. Overallб I like most of the changes

2024-05-24 12:42 UTC, David-cripto commented on README.md
> +pip install -e .
-e - editable mode, need only for developers

2024-05-24 12:42 UTC, David-cripto commented on scripts/sampling/sample2d.py
> +    parser.add_argument("--save_raw_data", action="store_true", help="save raw data (not only plots)")
What is it?

2024-05-24 12:42 UTC, David-cripto commented on scripts/sampling/sample2d.py
> +    experiment_name = Path(opt.ckpt_path).parts[-2]
why -2?

2024-05-24 12:42 UTC, David-cripto commented on scripts/train/train2d.py
> -    os.makedirs(opt.ckpt_path, exist_ok=True)
Why did you delete it?

2024-05-24 12:42 UTC, David-cripto commented on requirements.txt
> +ipdb
We should add version of the libs. I was too lazy to do it, but we need to do it

2024-05-24 12:42 UTC, David-cripto commented on scripts/train/train.py
> +    parser.add_argument("--c_in", type=int, default=3, help="in channels") # TODO better to set 3 and forget about this
Mb, you're right. I just was thinking about expanding this to other domains(not only for pictures)

2024-05-24 12:42 UTC, David-cripto commented on scripts/train/train.py
> +    val_dataloader = DataLoader(val_pair_dataset, opt.val_log, shuffle = True)
It's bad to shuffle validation dataloader, 'cause order here is important for logging images

2024-05-24 12:42 UTC, David-cripto commented on toysb/utils.py
> +    checkpoint = th.load(opt.ckpt_path, map_location="cpu") #FIXME possible bug with ckpt_path
What's kind of the bug here?

2024-05-24 12:42 UTC, David-cripto commented on toysb/utils.py
> +        pass
Why do you need to save it?

2024-05-25 14:11 UTC, ocenandor commented on scripts/train/train2d.py
> -    os.makedirs(opt.ckpt_path, exist_ok=True)
I propose the following structure of loggi(ng files
```
.log # from --log-dir
  |  — experiment_name # from --name
     |  — tensorboard_logs.tfevents
     |  — ckpt_1.pt
     | ...
     |  — ckpt_n.pt
```

Also change code in `sampling.py` for convinient argumebts setting according ti this structure

So, there is no need to create a ckpt_path

2024-05-25 14:16 UTC, ocenandor commented on toysb/utils.py
> +    checkpoint = th.load(opt.ckpt_path, map_location="cpu") #FIXME possible bug with ckpt_path
Mark this, because don't manually check this function after changing arguments in train and sample

2024-05-25 14:17 UTC, ocenandor commented on toysb/utils.py
> +        pass
drawing trajectories

2024-05-25 14:17 UTC, ocenandor commented on scripts/sampling/sample2d.py
> +    parser.add_argument("--save_raw_data", action="store_true", help="save raw data (not only plots)")
For drawing trajectories

2024-05-25 14:22 UTC, ocenandor commented on toysb/utils.py
> +    checkpoint = th.load(opt.ckpt_path, map_location="cpu") #FIXME possible bug with ckpt_path
But it works, everything's fine

2024-05-25 14:25 UTC, ocenandor commented on scripts/sampling/sample2d.py
> +    experiment_name = Path(opt.ckpt_path).parts[-2]
Log folder is formed according to the naming used in train procedure

2024-05-25 14:31 UTC, ocenandor commented on toysb/datasets/dataset.py
`PAIRED_MODE = True` if we use setups like mnist <-> emnist

For super-resolution task `PAIRED_MODE = False` and the the old logic and code is used

```
self.indexes = [
    get_correspondance_index(name) for name in [opt.dataset1, opt.dataset2]
]
```
Here (lines 68-70) get bicection between labels of different datasets (0 = A, 1 = S, 2 = F, etc. fpr emnist <-> mnist)

Further (71-74) get bicection between samples of corresponding labels

`self.raw_idx` (76) - just usual index used for __getitem __

2024-06-01 13:59 UTC, David-cripto approved these changes

2024-06-01 13:59 UTC, merged